/*
 * This source file was generated by the Gradle 'init' task
 */
package com.qi.proguard

import groovy.lang.GroovyObject
import org.apache.commons.io.FileUtils
import org.gradle.api.NamedDomainObjectContainer
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.Configuration
import org.gradle.api.tasks.bundling.Zip
import proguard.gradle.ProGuardTask
import java.io.File

/**
 * A simple 'hello world' plugin.
 */
class ProguardPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        var version = project.version
        val ideaSandBoxPluginLibFile: File =
            project.layout.buildDirectory.file("idea-sandbox/plugins/${project.name}/lib").get().asFile
        val searchableOptionFile: File = project.layout.buildDirectory.file("libsSearchableOptions/lib").get().asFile
        val outputDir: File = project.layout.buildDirectory.file("output").get().asFile
        var outputLibDir = File(outputDir, "${project.name}-${version}/lib")
        var proguardChangeLogPath = "${outputLibDir.parent}/${project.name}-${version}-ProGuard-ChangeLog.txt"
        var inJarsPath = "${outputLibDir.absolutePath}/instrumented-${project.name}-${version}.jar"
        var outJarsPath = "${outputLibDir.absolutePath}/obscure-${project.name}-${version}.jar"
        project.gradle.projectsEvaluated {
            version = project.version
            outputLibDir = File(outputDir, "${project.name}-${version}/lib")
            proguardChangeLogPath =
                "${outputLibDir.parent}/${project.name}-${version}-ProGuard-ChangeLog.txt"
            inJarsPath = "${outputLibDir.absolutePath}/instrumented-${project.name}-${version}.jar"
            outJarsPath = "${outputLibDir.absolutePath}/obscure-${project.name}-${version}.jar"
        }

        val proguardBuildPluginTaskProvide =
            project.tasks.register("proguardBuildPlugin", ProGuardTask::class.java) { task ->
                task.dependsOn("buildPlugin")
                println("proguard configuration")
                task.description = "build and proguard plugin project"
                task.group = "archive"
                // 配置混淆开始==================================>
                task.verbose()
                task.injars(inJarsPath)
                task.outjars(outJarsPath)
                task.configuration(File("proguard.pro"))
                val javaHome = System.getProperty("java.home")
                File("$javaHome/jmods/").listFiles()?.forEach { task.libraryjars(it.absolutePath) }
                val compilePath = (project.configurations as GroovyObject).getProperty("compileClasspath")
                task.libraryjars(compilePath)
                task.dontshrink()
                task.dontoptimize()
                task.adaptclassstrings("**.xml")
                task.adaptresourcefilecontents("**.xml")
                task.adaptresourcefilenames()
                task.printmapping(proguardChangeLogPath)
                // Allow methods with the same signature, except for the return type,
                // to get the same obfuscation name.
                task.overloadaggressively()
//                task.dontwarn()
                task.target(version.toString())
                task.optimizationpasses(9)
                task.allowaccessmodification()
                // Put all obfuscated classes into the nameless root package.
                task.repackageclasses("")
                // 配置混淆结束<==================================
                task.doFirst {
                    println("proguard do first")
                    if (outputDir.exists()) {
                        FileUtils.deleteDirectory(outputDir)
                    }
                    FileUtils.forceMkdir(outputLibDir)
                    FileUtils.copyDirectory(
                        ideaSandBoxPluginLibFile,
                        outputLibDir
                    )
                    FileUtils.copyDirectory(
                        searchableOptionFile,
                        outputLibDir
                    )
                }

                task.doLast {
                    FileUtils.forceDelete(File(inJarsPath))
                }
            }

        project.tasks.register("archive", Zip::class.java) { task ->
            task.dependsOn(proguardBuildPluginTaskProvide.get())
            task.description = "archive proguard files"
            task.group = "archive"
            task.from(outputLibDir)
            task.include("*")
            task.include("*/*")
            task.into("${project.name}/lib")
            task.archiveFileName.convention("${outputDir.path}/${project.name}-${version}.zip")
            println("archiveFile: ${task.archiveFile.get().asFile.path}")
        }
    }
}
